/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package solucion2;

import ht1javadiegoyoc.JfrmMenu;
import java.awt.Color;

/**
 *
 * @author ChocoChiwi
 */
public class JfrmSolucion2 extends javax.swing.JFrame {
    
    /**
     * Creates new form JfrmSolucion2
     */
    FuncionesTv funciones = new FuncionesTv();
    private String a;
    public JfrmSolucion2() {
        initComponents();
        this.getContentPane().setBackground(Color.black);
        this.jLblPantalla.setOpaque(true);
        this.jLblPantalla.setBackground(Color.red);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblEtiquetaCanales = new javax.swing.JLabel();
        jLblEtiquetaTv = new javax.swing.JLabel();
        jLblEtiquetaVolumen = new javax.swing.JLabel();
        jBtnVolumenSubir = new javax.swing.JButton();
        jBtnVolumenBajar = new javax.swing.JButton();
        jBtnCanalAbajo = new javax.swing.JButton();
        jBtnCanalArriba = new javax.swing.JButton();
        jBtnEstado = new javax.swing.JButton();
        jLblPantalla = new javax.swing.JLabel();
        jBtnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLblEtiquetaCanales.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLblEtiquetaCanales.setForeground(new java.awt.Color(255, 255, 255));
        jLblEtiquetaCanales.setText("Canales");

        jLblEtiquetaTv.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLblEtiquetaTv.setForeground(new java.awt.Color(255, 255, 255));
        jLblEtiquetaTv.setText("Solución 2 Control TV 6000");

        jLblEtiquetaVolumen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLblEtiquetaVolumen.setForeground(new java.awt.Color(255, 255, 255));
        jLblEtiquetaVolumen.setText("Volumen");

        jBtnVolumenSubir.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jBtnVolumenSubir.setText("+");
        jBtnVolumenSubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVolumenSubirActionPerformed(evt);
            }
        });

        jBtnVolumenBajar.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jBtnVolumenBajar.setText("-");
        jBtnVolumenBajar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVolumenBajarActionPerformed(evt);
            }
        });

        jBtnCanalAbajo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jBtnCanalAbajo.setText("-");
        jBtnCanalAbajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCanalAbajoActionPerformed(evt);
            }
        });

        jBtnCanalArriba.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jBtnCanalArriba.setText("+");
        jBtnCanalArriba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCanalArribaActionPerformed(evt);
            }
        });

        jBtnEstado.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBtnEstado.setText("Encender");
        jBtnEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEstadoActionPerformed(evt);
            }
        });

        jLblPantalla.setBackground(new java.awt.Color(255, 51, 51));
        jLblPantalla.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLblPantalla.setForeground(new java.awt.Color(255, 255, 255));
        jLblPantalla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblPantalla.setText("Apagada");

        jBtnRegresar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnRegresar.setText("Regresar a Menú Principal");
        jBtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblEtiquetaVolumen)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jBtnVolumenSubir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jBtnVolumenBajar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLblEtiquetaTv)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jBtnCanalArriba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLblEtiquetaCanales, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jBtnCanalAbajo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblEtiquetaTv)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblEtiquetaVolumen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnVolumenSubir)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnVolumenBajar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblEtiquetaCanales)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnCanalArriba)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnCanalAbajo)))
                .addGap(16, 16, 16)
                .addComponent(jBtnEstado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnRegresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnVolumenSubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVolumenSubirActionPerformed
        // TODO add your handling code here:
        jLblPantalla.setText(funciones.subirVolumen());
    }//GEN-LAST:event_jBtnVolumenSubirActionPerformed

    private void jBtnVolumenBajarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVolumenBajarActionPerformed
        // TODO add your handling code here:
        jLblPantalla.setText(funciones.bajarVolumen());
    }//GEN-LAST:event_jBtnVolumenBajarActionPerformed

    private void jBtnCanalAbajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCanalAbajoActionPerformed
        // TODO add your handling code here:
        jLblPantalla.setText(funciones.canalAbajo());
    }//GEN-LAST:event_jBtnCanalAbajoActionPerformed

    private void jBtnCanalArribaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCanalArribaActionPerformed
        // TODO add your handling code here:
        jLblPantalla.setText(funciones.canalArriba());
    }//GEN-LAST:event_jBtnCanalArribaActionPerformed

    private void jBtnEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEstadoActionPerformed
        // TODO add your handling code here:
        funciones.asignarEstado(jLblPantalla.getText());
        funciones.asignarTexto(jBtnEstado.getText());
               
        a=funciones.cambiarColor();
        if (a=="red") {
            this.jLblPantalla.setBackground(Color.green);
        }
        else{
            this.jLblPantalla.setBackground(Color.red);
        }
               
        jLblPantalla.setText(funciones.cambiarEstado());
        jBtnEstado.setText(funciones.cambiarTextoBoton());
 
    }//GEN-LAST:event_jBtnEstadoActionPerformed

    private void jBtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegresarActionPerformed
        // TODO add your handling code here:
        JfrmMenu FrmMenu = new JfrmMenu();
        FrmMenu.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jBtnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfrmSolucion2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfrmSolucion2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfrmSolucion2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfrmSolucion2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfrmSolucion2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCanalAbajo;
    private javax.swing.JButton jBtnCanalArriba;
    private javax.swing.JButton jBtnEstado;
    private javax.swing.JButton jBtnRegresar;
    private javax.swing.JButton jBtnVolumenBajar;
    private javax.swing.JButton jBtnVolumenSubir;
    private javax.swing.JLabel jLblEtiquetaCanales;
    private javax.swing.JLabel jLblEtiquetaTv;
    private javax.swing.JLabel jLblEtiquetaVolumen;
    private javax.swing.JLabel jLblPantalla;
    // End of variables declaration//GEN-END:variables
}
