/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ht1javadiegoyoc;

import java.awt.Color;
import solucion1.JfrmSolucion1;
import solucion2.JfrmSolucion2;
import solucion3.JfrmSolucion3;
import solucion4.JfrmSolucion4;
import solucion5.JfrmSolucion5;

/**
 *
 * @author ChocoChiwi
 */
public class JfrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form JfrmMenu
     */
    
    public JfrmMenu() {
        initComponents();
        this.getContentPane().setBackground(Color.orange);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblTitulo = new javax.swing.JLabel();
        jLblEnunciado = new javax.swing.JLabel();
        jBtnSolucion1 = new javax.swing.JButton();
        jBtnSolucion2 = new javax.swing.JButton();
        jBtnSolucion3 = new javax.swing.JButton();
        jBtnSolucion4 = new javax.swing.JButton();
        jBtnSolucion5 = new javax.swing.JButton();
        jBtnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú");
        setResizable(false);

        jLblTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLblTitulo.setText("Hoja de trabajo #1");

        jLblEnunciado.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLblEnunciado.setText("Seleccione la opción que desee utilizar");

        jBtnSolucion1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnSolucion1.setText("Ir a Solución 1");
        jBtnSolucion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSolucion1ActionPerformed(evt);
            }
        });

        jBtnSolucion2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnSolucion2.setText("Ir a Solución 2");
        jBtnSolucion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSolucion2ActionPerformed(evt);
            }
        });

        jBtnSolucion3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnSolucion3.setText("Ir a Solución 3");
        jBtnSolucion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSolucion3ActionPerformed(evt);
            }
        });

        jBtnSolucion4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnSolucion4.setText("Ir a Solución 4");
        jBtnSolucion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSolucion4ActionPerformed(evt);
            }
        });

        jBtnSolucion5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnSolucion5.setText("Ir a Solución 5");
        jBtnSolucion5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSolucion5ActionPerformed(evt);
            }
        });

        jBtnSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnSalir.setText("Salir");
        jBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnSolucion3)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnSolucion4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnSolucion1)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnSolucion2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnSolucion5)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLblTitulo)))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLblEnunciado)
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblEnunciado, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnSolucion1)
                    .addComponent(jBtnSolucion2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnSolucion3)
                    .addComponent(jBtnSolucion4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnSolucion5)
                    .addComponent(jBtnSalir))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSolucion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSolucion1ActionPerformed
        // TODO add your handling code here:
        JfrmSolucion1 frmSolucion1=new JfrmSolucion1();
        frmSolucion1.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_jBtnSolucion1ActionPerformed

    private void jBtnSolucion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSolucion2ActionPerformed
        // TODO add your handling code here:
         JfrmSolucion2 frmSolucion2=new JfrmSolucion2();

        frmSolucion2.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBtnSolucion2ActionPerformed

    private void jBtnSolucion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSolucion3ActionPerformed
        // TODO add your handling code here:
        JfrmSolucion3 frmSolucion3=new JfrmSolucion3();
        frmSolucion3.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBtnSolucion3ActionPerformed

    private void jBtnSolucion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSolucion4ActionPerformed
        // TODO add your handling code here:
        JfrmSolucion4 frmSolucion4=new JfrmSolucion4();
        frmSolucion4.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBtnSolucion4ActionPerformed

    private void jBtnSolucion5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSolucion5ActionPerformed
        // TODO add your handling code here:
        JfrmSolucion5 frmSolucion5=new JfrmSolucion5();
        frmSolucion5.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBtnSolucion5ActionPerformed

    private void jBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBtnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnSalir;
    private javax.swing.JButton jBtnSolucion1;
    private javax.swing.JButton jBtnSolucion2;
    private javax.swing.JButton jBtnSolucion3;
    private javax.swing.JButton jBtnSolucion4;
    private javax.swing.JButton jBtnSolucion5;
    private javax.swing.JLabel jLblEnunciado;
    private javax.swing.JLabel jLblTitulo;
    // End of variables declaration//GEN-END:variables
}
