/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package solucion1;

import java.awt.Color;
import javax.swing.JOptionPane;
import parcialjavadiegoyoc.JFrmMenu;

/**
 *
 * @author ChocoChiwi
 */
public class JFrmSolucion1 extends javax.swing.JFrame {

    /**
     * Creates new form JFrmSolucion1
     */
    ProcesosSolucion1 objeto = new ProcesosSolucion1();
    
    public JFrmSolucion1() {
        initComponents();
        this.getContentPane().setBackground(Color.black);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jLstEnunciado1 = new javax.swing.JList<>();
        jLblTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLblNumero = new javax.swing.JLabel();
        jTxtNum = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLstResultado = new javax.swing.JList<>();
        jBtnOpcion1 = new javax.swing.JButton();
        jBtnOpcion2 = new javax.swing.JButton();
        jBtnOpcion3 = new javax.swing.JButton();
        jBtnOpcion4 = new javax.swing.JButton();
        jBtnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Solución 1");
        setResizable(false);

        jLstEnunciado1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Solicitar un valor numérico entero:", "1) Mostrar de 1 en 1 desde el 1 hasta llegar al valor ingresado.", "2) Mostrar de 2 en 2 desde el 2 hasta el valor ingresado.", "3) Mostrar de forma inversa los valores.", "4) Mostrar de forma inversa los valores de 3 en 3." };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jLstEnunciado1);

        jLblTitulo.setFont(new java.awt.Font("Cooper Black", 1, 24)); // NOI18N
        jLblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLblTitulo.setText("Solución 1");

        jLblNumero.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLblNumero.setForeground(new java.awt.Color(255, 255, 255));
        jLblNumero.setText("Ingrese un valor numérico");

        jTxtNum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTxtNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNumActionPerformed(evt);
            }
        });
        jTxtNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtNumKeyTyped(evt);
            }
        });

        jScrollPane2.setViewportView(jLstResultado);

        jBtnOpcion1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnOpcion1.setText("Opción 1");
        jBtnOpcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOpcion1ActionPerformed(evt);
            }
        });

        jBtnOpcion2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnOpcion2.setText("Opción 2");
        jBtnOpcion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOpcion2ActionPerformed(evt);
            }
        });

        jBtnOpcion3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnOpcion3.setText("Opción 3");
        jBtnOpcion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOpcion3ActionPerformed(evt);
            }
        });

        jBtnOpcion4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnOpcion4.setText("Opción 4");
        jBtnOpcion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOpcion4ActionPerformed(evt);
            }
        });

        jBtnRegresar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnRegresar.setText("Regresar al Menú");
        jBtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLblTitulo)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLblNumero)
                        .addGap(31, 31, 31)
                        .addComponent(jTxtNum, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnOpcion1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnOpcion2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnOpcion3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnOpcion4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnRegresar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLblTitulo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblNumero)
                    .addComponent(jTxtNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnOpcion1)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnOpcion2)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnOpcion3)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnOpcion4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnRegresar))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNumActionPerformed

    private void jTxtNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtNumKeyTyped
        // TODO add your handling code here:
        jTxtNum.setText(jTxtNum.getText().trim());

        char validar=evt.getKeyChar(); //evt es un Key Event
        if (!Character.isDigit(validar)) {
            
            evt.consume(); //Consume este evento para que la fuente que lo originó no lo procese de manera predeterminada.
            //JOptionPane.showMessageDialog(rootPane, "Solo se permite el uso de números"); //rootPane crear ventanas
        }

    }//GEN-LAST:event_jTxtNumKeyTyped

    private void jBtnOpcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOpcion1ActionPerformed
        // TODO add your handling code here:
        if (jTxtNum.getText().isEmpty()) {
            
            jLstResultado.setModel(objeto.vacio());
        }
        else{
            objeto.setNum(Integer.parseInt(jTxtNum.getText()));
            jLstResultado.setModel(objeto.llenarLista());
        }
        
    }//GEN-LAST:event_jBtnOpcion1ActionPerformed

    private void jBtnOpcion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOpcion2ActionPerformed
        // TODO add your handling code here:
        if (jTxtNum.getText().isEmpty()) {
            
            jLstResultado.setModel(objeto.vacio());
        }
        else{
            objeto.setNum(Integer.parseInt(jTxtNum.getText()));
            jLstResultado.setModel(objeto.llenarLista2());
        }
    }//GEN-LAST:event_jBtnOpcion2ActionPerformed

    private void jBtnOpcion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOpcion3ActionPerformed
        // TODO add your handling code here:
        if (jTxtNum.getText().isEmpty()) {
            
            jLstResultado.setModel(objeto.vacio());
        }
        else{
            objeto.setNum(Integer.parseInt(jTxtNum.getText()));
            jLstResultado.setModel(objeto.llenarLista3());
        }
    }//GEN-LAST:event_jBtnOpcion3ActionPerformed

    private void jBtnOpcion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOpcion4ActionPerformed
        // TODO add your handling code here:
        if (jTxtNum.getText().isEmpty()) {
            
            jLstResultado.setModel(objeto.vacio());
        }
        else{
            objeto.setNum(Integer.parseInt(jTxtNum.getText()));
            jLstResultado.setModel(objeto.llenarLista4());
        }
    }//GEN-LAST:event_jBtnOpcion4ActionPerformed

    private void jBtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegresarActionPerformed
        // TODO add your handling code here:
        JFrmMenu Menu = new JFrmMenu();
        Menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBtnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmSolucion1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmSolucion1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmSolucion1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmSolucion1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmSolucion1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnOpcion1;
    private javax.swing.JButton jBtnOpcion2;
    private javax.swing.JButton jBtnOpcion3;
    private javax.swing.JButton jBtnOpcion4;
    private javax.swing.JButton jBtnRegresar;
    private javax.swing.JLabel jLblNumero;
    private javax.swing.JLabel jLblTitulo;
    private javax.swing.JList<String> jLstEnunciado1;
    private javax.swing.JList<String> jLstResultado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTxtNum;
    // End of variables declaration//GEN-END:variables
}
