/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package solucion3;

import java.awt.Color;
import parcialjavadiegoyoc.JFrmMenu;

/**
 *
 * @author ChocoChiwi
 */
public class JFrmSolucion3 extends javax.swing.JFrame {

    /** Creates new form JFrmSolucion3 */
    ProcesosSolucion3 objeto=new ProcesosSolucion3();
    public JFrmSolucion3() {
        initComponents();
        this.getContentPane().setBackground(Color.black);
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblNumero2 = new javax.swing.JLabel();
        jTxtNum2 = new javax.swing.JTextField();
        jBtnRegresar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLstResultado = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLstEnunciado3 = new javax.swing.JList<>();
        jLblTitulo = new javax.swing.JLabel();
        jLblNumero1 = new javax.swing.JLabel();
        jTxtNum1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jBtnOpcion1 = new javax.swing.JButton();
        jBtnOpcion2 = new javax.swing.JButton();
        jBtnOpcion3 = new javax.swing.JButton();
        jBtnOpcion4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Solución 3");
        setResizable(false);

        jLblNumero2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLblNumero2.setForeground(new java.awt.Color(255, 255, 255));
        jLblNumero2.setText("Ingrese segundo valor numérico");

        jTxtNum2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTxtNum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNum2ActionPerformed(evt);
            }
        });
        jTxtNum2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtNum2KeyTyped(evt);
            }
        });

        jBtnRegresar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnRegresar.setText("Regresar al Menú");
        jBtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRegresarActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jLstResultado);

        jLstEnunciado3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Solicitar 2 valores enteros:", "1) Listar los números pares existentes en el rango", "2) Listar los números impares existente en el rango", "3) Mostrar los valores múltiplos de 3", "4) Mostrar los valores múltiplos de 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jLstEnunciado3);

        jLblTitulo.setFont(new java.awt.Font("Cooper Black", 1, 24)); // NOI18N
        jLblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLblTitulo.setText("Solución 3");

        jLblNumero1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLblNumero1.setForeground(new java.awt.Color(255, 255, 255));
        jLblNumero1.setText("Ingrese primer valor numérico");

        jTxtNum1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTxtNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNum1ActionPerformed(evt);
            }
        });
        jTxtNum1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtNum1KeyTyped(evt);
            }
        });

        jBtnOpcion1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnOpcion1.setText("Opción 1");
        jBtnOpcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOpcion1ActionPerformed(evt);
            }
        });

        jBtnOpcion2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnOpcion2.setText("Opción 2");
        jBtnOpcion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOpcion2ActionPerformed(evt);
            }
        });

        jBtnOpcion3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnOpcion3.setText("Opción 3");
        jBtnOpcion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOpcion3ActionPerformed(evt);
            }
        });

        jBtnOpcion4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnOpcion4.setText("Opción 4");
        jBtnOpcion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOpcion4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLblTitulo))
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnOpcion1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnOpcion2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnOpcion4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnOpcion3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLblNumero1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTxtNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLblNumero2)
                            .addGap(31, 31, 31)
                            .addComponent(jTxtNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLblTitulo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblNumero1)
                    .addComponent(jTxtNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblNumero2)
                    .addComponent(jTxtNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnOpcion1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnOpcion2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnOpcion3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(jBtnOpcion4)
                        .addGap(37, 37, 37)
                        .addComponent(jBtnRegresar))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNum2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNum2ActionPerformed

    private void jTxtNum2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtNum2KeyTyped
        // TODO add your handling code here:
        jTxtNum2.setText(jTxtNum2.getText().trim()); //evita los espacios

        char validar=evt.getKeyChar(); //evt es un Key Event
        if (!Character.isDigit(validar)) {

            evt.consume(); //Consume este evento para que la fuente que lo originó no lo procese de manera predeterminada.
            //JOptionPane.showMessageDialog(rootPane, "Solo se permite el uso de números"); //rootPane crear ventanas
        }
    }//GEN-LAST:event_jTxtNum2KeyTyped

    private void jBtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegresarActionPerformed
        // TODO add your handling code here:
        JFrmMenu Menu = new JFrmMenu();
        Menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBtnRegresarActionPerformed

    private void jTxtNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNum1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNum1ActionPerformed

    private void jTxtNum1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtNum1KeyTyped
        // TODO add your handling code here:
        jTxtNum1.setText(jTxtNum1.getText().trim()); //evita los espacios

        char validar=evt.getKeyChar(); //evt es un Key Event
        if (!Character.isDigit(validar)) {

            evt.consume(); //Consume este evento para que la fuente que lo originó no lo procese de manera predeterminada.
            //JOptionPane.showMessageDialog(rootPane, "Solo se permite el uso de números"); //rootPane crear ventanas
        }
    }//GEN-LAST:event_jTxtNum1KeyTyped

    private void jBtnOpcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOpcion1ActionPerformed
        // TODO add your handling code here:
        if (jTxtNum1.getText().isEmpty() || jTxtNum2.getText().isEmpty()) {

            jLstResultado.setModel(objeto.vacio());
        }
        else{
            objeto.setNum1(Integer.parseInt(jTxtNum1.getText()));
            objeto.setNum2(Integer.parseInt(jTxtNum2.getText()));
            jLstResultado.setModel(objeto.llenarLista1());
        }
    }//GEN-LAST:event_jBtnOpcion1ActionPerformed

    private void jBtnOpcion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOpcion2ActionPerformed
        // TODO add your handling code here:
        if (jTxtNum1.getText().isEmpty() || jTxtNum2.getText().isEmpty()) {

            jLstResultado.setModel(objeto.vacio());
        }
        else{
            objeto.setNum1(Integer.parseInt(jTxtNum1.getText()));
            objeto.setNum2(Integer.parseInt(jTxtNum2.getText()));
            jLstResultado.setModel(objeto.llenarLista2());
        }
    }//GEN-LAST:event_jBtnOpcion2ActionPerformed

    private void jBtnOpcion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOpcion3ActionPerformed
        // TODO add your handling code here:
        if (jTxtNum1.getText().isEmpty() || jTxtNum2.getText().isEmpty()) {

            jLstResultado.setModel(objeto.vacio());
        }
        else{
            objeto.setNum1(Integer.parseInt(jTxtNum1.getText()));
            objeto.setNum2(Integer.parseInt(jTxtNum2.getText()));
            jLstResultado.setModel(objeto.llenarLista3());
        }
    }//GEN-LAST:event_jBtnOpcion3ActionPerformed

    private void jBtnOpcion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOpcion4ActionPerformed
        // TODO add your handling code here:
        if (jTxtNum1.getText().isEmpty() || jTxtNum2.getText().isEmpty()) {

            jLstResultado.setModel(objeto.vacio());
        }
        else{
            objeto.setNum1(Integer.parseInt(jTxtNum1.getText()));
            objeto.setNum2(Integer.parseInt(jTxtNum2.getText()));
            jLstResultado.setModel(objeto.llenarLista4());
        }
    }//GEN-LAST:event_jBtnOpcion4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmSolucion3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmSolucion3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmSolucion3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmSolucion3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmSolucion3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnOpcion1;
    private javax.swing.JButton jBtnOpcion2;
    private javax.swing.JButton jBtnOpcion3;
    private javax.swing.JButton jBtnOpcion4;
    private javax.swing.JButton jBtnRegresar;
    private javax.swing.JLabel jLblNumero1;
    private javax.swing.JLabel jLblNumero2;
    private javax.swing.JLabel jLblTitulo;
    private javax.swing.JList<String> jLstEnunciado3;
    private javax.swing.JList<String> jLstResultado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTxtNum1;
    private javax.swing.JTextField jTxtNum2;
    // End of variables declaration//GEN-END:variables

}
